# Generated by Django 5.2.11 on 2026-05-04 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the task was marked done', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('design', 'Design'), ('build', 'Build'), ('test', 'Test'), ('ship', 'Ship')], default='build', max_length=20),
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why this task is blocked')),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('snooze_count', models.PositiveIntegerField(default=0, help_text='Times this blocker has been snoozed')),
                ('downstream_count', models.PositiveIntegerField(default=0, help_text='Tasks waiting on this blocker')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_blockers', to='projects.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='projects.project')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_blockers', to='projects.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_records', to='projects.task')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('backlog_locked', models.BooleanField(default=False, help_text='Prevents new tasks from entering this sprint')),
                ('review_sla_hours', models.PositiveIntegerField(blank=True, help_text='Max hours a task can sit in review before triggering alert', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
        migrations.CreateModel(
            name='TaskStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='projects.task')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('done_tasks', models.PositiveIntegerField(default=0)),
                ('blocked_tasks', models.PositiveIntegerField(default=0)),
                ('added_tasks', models.PositiveIntegerField(default=0, help_text='Tasks added after sprint start (scope creep)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.sprint')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('sprint', 'date')},
            },
        ),
    ]
