# Generated by Django 5.2.11 on 2026-05-04 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_completed_at_task_stage_blocker_sprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_risk_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_risk_label',
            field=models.CharField(blank=True, default='', help_text='Cached risk label for hysteresis — prevents flapping', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='timezone_name',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA timezone for day boundary calculations', max_length=50),
        ),
        migrations.CreateModel(
            name='RiskLabelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_label', models.CharField(blank=True, default='', max_length=20)),
                ('to_label', models.CharField(max_length=20)),
                ('reason', models.TextField(help_text='What signal triggered the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(help_text='Type of suggestion dismissed', max_length=50)),
                ('suggestion_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_dismissals', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
