# Generated by Django 5.2.11 on 2026-05-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_last_risk_changed_at_project_last_risk_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.UUIDField(blank=True, help_text='UUID of related blocker or task', null=True),
        ),
    ]
