# Generated by Django 5.2.11 on 2026-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_related_id_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='require_dri',
            field=models.BooleanField(default=False, help_text='Policy: every active task must have an assignee to advance'),
        ),
        migrations.AddField(
            model_name='sprintsnapshot',
            name='is_backfilled',
            field=models.BooleanField(default=False, help_text='True if reconstructed from logs, not live'),
        ),
    ]
