# Generated by Django 5.2.11 on 2026-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_sprint_require_dri_sprintsnapshot_is_backfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_throttle_count', models.PositiveIntegerField(default=3, help_text='Dismissals of same type within window to suppress suggestion')),
                ('dismissal_throttle_window_days', models.PositiveIntegerField(default=7, help_text='Rolling window (days) for dismissal throttle')),
                ('dismissal_decay_halflife_days', models.FloatField(default=7.0, help_text='Half-life (days) for dismissal score decay')),
                ('hysteresis_pace_threshold', models.FloatField(default=0.8, help_text='Pace must reach this fraction of required to demote from Critical')),
                ('blocker_age_critical_days', models.PositiveIntegerField(default=2, help_text='Days before a blocker auto-promotes to critical')),
                ('blocker_downstream_critical', models.PositiveIntegerField(default=3, help_text='Downstream task count to auto-promote blocker to critical')),
                ('blocker_deadline_critical_days', models.PositiveIntegerField(default=7, help_text='Project deadline within N days auto-promotes blockers to critical')),
                ('escalation_unignorable_days', models.PositiveIntegerField(default=3, help_text='Escalated Critical blocker becomes unignorable after N days')),
                ('stale_dwell_research', models.PositiveIntegerField(default=5)),
                ('stale_dwell_design', models.PositiveIntegerField(default=4)),
                ('stale_dwell_build', models.PositiveIntegerField(default=3)),
                ('stale_dwell_test', models.PositiveIntegerField(default=2)),
                ('stale_dwell_ship', models.PositiveIntegerField(default=1)),
                ('default_weekly_capacity', models.FloatField(default=40.0, help_text="Default weekly capacity when UserProfile doesn't specify")),
                ('diagnostic_weighting_version', models.PositiveIntegerField(default=2, help_text='Increment when weighting math changes — trends only compare within same version')),
                ('critical_path_weight_multiplier', models.FloatField(default=2.0, help_text='Weight multiplier for tasks on the critical path in diagnostic scoring')),
                ('brief_resurfacing_days', models.PositiveIntegerField(default=3, help_text='Days a Critical project must persist before re-surfacing in brief')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Configuration',
                'verbose_name_plural': 'Dashboard Configuration',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of date ranges when unavailable: [{'start': 'YYYY-MM-DD', 'end': 'YYYY-MM-DD', 'reason': 'PTO'}]"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_capacity_hours',
            field=models.FloatField(default=40.0, help_text='Available hours per week (accounts for part-time, role, etc.)'),
        ),
    ]
